---
- hosts: all
  become: true
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
    - name: Install openvpn and tools
      yum:
        name:
          - openvpn
          - iperf3
          - libselinux-python
        state: present
    - name: Set SElinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

- hosts: server
  become: true
  roles:
    - role: openvpn-server
      simple_ovpn: true

- hosts: client
  become: true
  roles:
    - role: openvpn-client